services:
  music-dl:
    image: guohuiyuan/go-music-dl:latest
    container_name: music-dl
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # ğŸŒŸ æ ¸å¿ƒä¿®æ­£ï¼šæŒ‚è½½åˆ°ç¨‹åºå®é™…çš„è¿è¡Œç›®å½• /home/appuser/data ä¸‹
      - ./data:/home/appuser/data
    environment:
      - TZ=Asia/Shanghai
    command: [ "./music-dl", "web", "--port", "8080", "--no-browser", "--vg-cover", "--vg-audio", "--vg-lyric", "--vg-export" ]
